
//AUTOGENERATED FILE: DO NOT EDIT
#include "MINX/Game.h"
#include "MINX/GameTime.h"
#include "MINX/Input/Keyboard.h"
#ifndef MINX_PONG_H_
#define MINX_PONG_H_

using namespace MINX;

namespace MINX_MINX_PONG
{
	class MINX_Pong : public Game
	{
		public:
			MINX_Pong();
			void Initialize();
			void LoadContent();
			void UnloadContent();
			void Update(GameTime * gameTime);
			void Draw(GameTime * gameTime);
	};
}

#endif
